# Generated by Django 4.0.3 on 2022-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('tel', models.IntegerField(max_length=50, verbose_name='Телефон')),
                ('work', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'UserContact',
                'verbose_name_plural': 'UserContact',
            },
        ),
    ]
