# Generated by Django 4.0.3 on 2022-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='tel',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
    ]
