# Generated by Django 4.0.3 on 2022-03-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_location', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_water', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Контролируемая вода',
                'verbose_name_plural': 'Контролируемая вода',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | БОС',
                'verbose_name_plural': 'Отбор проб | БОС',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | МОС',
                'verbose_name_plural': 'Отбор проб | МОС',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | УГОВ',
                'verbose_name_plural': 'Отбор проб | УГОВ',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | БОВ-2',
                'verbose_name_plural': 'Отбор проб | БОВ-2',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | БОВ-1',
                'verbose_name_plural': 'Отбор проб | БОВ-1',
            },
        ),
        migrations.CreateModel(
            name='LocationPlace1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_locationplace', models.CharField(max_length=100, verbose_name='Название')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
            ],
            options={
                'verbose_name': 'Отбор проб | Водоблок-2',
                'verbose_name_plural': 'Отбор проб | Водоблок-2',
            },
        ),
    ]
