# Generated by Django 4.0.3 on 2022-03-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название компонента')),
                ('measurement', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('limits', models.CharField(blank=True, max_length=50, verbose_name='Допустимые нормы не более')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Периодичность отбора')),
                ('standards', models.CharField(blank=True, max_length=100, verbose_name='Наименование НД и методы испытаний')),
                ('recommendation1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Рекомендация выше нормы')),
                ('recommendation2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Рекомендация ниже нормы')),
            ],
        ),
        migrations.CreateModel(
            name='PlantUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название установки')),
            ],
            options={
                'verbose_name': 'Установка',
                'verbose_name_plural': 'Установки',
            },
        ),
        migrations.CreateModel(
            name='WaterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип воды')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Место отбора проб')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_site', to='projects.plantunit')),
                ('water_type', models.ManyToManyField(related_name='sampling_site', to='projects.watertype')),
            ],
            options={
                'verbose_name': 'Место отбора проб',
                'verbose_name_plural': 'Места отбора проб',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время анализа')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='projects.samplingsite')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.IntegerField(blank=True, null=True, verbose_name='Показатель')),
                ('component', models.ManyToManyField(related_name='result', to='projects.component')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='projects.sample')),
            ],
        ),
    ]
