# Generated by Django 4.0.3 on 2022-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='period_in_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения задачи в часах'),
        ),
    ]
