# Generated by Django 4.0.3 on 2022-03-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantLocation',
            new_name='PlantUnit',
        ),
        migrations.AlterModelOptions(
            name='components',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
    ]
