# Generated by Django 4.0.3 on 2022-03-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание задачи')),
                ('execution_period', models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения задачи в часах')),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='limits',
        ),
        migrations.AddField(
            model_name='component',
            name='limit_hi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не более'),
        ),
        migrations.AddField(
            model_name='component',
            name='limit_lo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не ниже'),
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название компонента'),
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи')),
                ('comp_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компонента')),
                ('sampling_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.samplingsite')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
