# Generated by Django 4.0.3 on 2022-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tasks_taskassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи'),
        ),
    ]
