# Generated by Django 4.0.3 on 2022-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_locationplace1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputComponent11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Нефтепродукт')),
                ('input_component2', models.IntegerField(verbose_name='Значение рН')),
                ('input_component3', models.IntegerField(verbose_name='Общие взвешенные твердые частицы')),
                ('input_component4', models.IntegerField(verbose_name='Фосфор')),
                ('input_component5', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component6', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component7', models.IntegerField(verbose_name='Солесодержание')),
                ('input_component8', models.IntegerField(verbose_name='Хлориды')),
                ('input_component9', models.IntegerField(verbose_name='Сульфаты')),
                ('input_component10', models.IntegerField(verbose_name='Жесткость кальциевая')),
                ('input_component12', models.IntegerField(verbose_name='Жесткость магниевая')),
                ('input_component13', models.IntegerField(verbose_name='Железо')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Показатель [1|1]',
                'verbose_name_plural': 'Input | Показатели [1|1]',
            },
        ),
    ]
