# Generated by Django 4.0.3 on 2022-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_plantlocation_plantunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='recommendation1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Рекомендация выше нормы'),
        ),
        migrations.AlterField(
            model_name='components',
            name='recommendation2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Рекомендация ниже нормы'),
        ),
    ]
