# Generated by Django 4.0.3 on 2022-04-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_taskassign_task_rename_task_task_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
