# Generated by Django 4.0.3 on 2022-03-31 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.status'),
        ),
    ]
