# Generated by Django 4.0.3 on 2022-03-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_components_recommendation1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Components',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='sampling_site',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='water_type',
        ),
        migrations.RemoveField(
            model_name='componentssite3',
            name='sampling_site',
        ),
        migrations.RemoveField(
            model_name='componentssite3',
            name='water_type',
        ),
        migrations.RemoveField(
            model_name='componentssite4',
            name='sampling_site',
        ),
        migrations.RemoveField(
            model_name='componentssite4',
            name='water_type',
        ),
        migrations.RemoveField(
            model_name='samplingsite',
            name='location',
        ),
        migrations.RemoveField(
            model_name='watertype',
            name='sampling_site',
        ),
        migrations.DeleteModel(
            name='ComponentsSite1',
        ),
        migrations.DeleteModel(
            name='ComponentsSite2',
        ),
        migrations.DeleteModel(
            name='ComponentsSite3',
        ),
        migrations.DeleteModel(
            name='ComponentsSite4',
        ),
        migrations.DeleteModel(
            name='PlantUnit',
        ),
        migrations.DeleteModel(
            name='SamplingSite',
        ),
        migrations.DeleteModel(
            name='WaterType',
        ),
    ]
