# Generated by Django 4.0.3 on 2022-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_taskassign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentssite1',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite10',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite2',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='hardness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='salt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Солесодержание'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные вещества'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='hardness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='salt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Солесодержание'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные вещества'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='hardness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='salt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Солесодержание'),
        ),
        migrations.AlterField(
            model_name='componentssite6',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AlterField(
            model_name='componentssite7',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая (кальций, мг/л)'),
        ),
        migrations.AlterField(
            model_name='componentssite7',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='componentssite8',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая (кальций, мг/л)'),
        ),
        migrations.AlterField(
            model_name='componentssite8',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='componentssite8',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукты'),
        ),
        migrations.AlterField(
            model_name='componentssite9',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая (кальций, мг/л)'),
        ),
        migrations.AlterField(
            model_name='componentssite9',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Железо'),
        ),
    ]
