# Generated by Django 4.0.3 on 2022-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tasks_taskassign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Срок выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи'),
        ),
    ]
