# Generated by Django 4.0.3 on 2022-03-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_indicator_result_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsSite1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='pH')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('active_subst', models.IntegerField(blank=True, null=True, verbose_name='Поверхностно-активные вещества (АПАВ)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component1', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component1', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('active_subst', models.IntegerField(blank=True, null=True, verbose_name='Поверхностно-активные вещества (АПАВ)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('oxygen_bio', models.IntegerField(blank=True, null=True, verbose_name='Биологическая потребность в кислороде (БПК5)')),
                ('phenols', models.IntegerField(blank=True, null=True, verbose_name='Фенолы')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Сульфаты')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо')),
                ('nitrate', models.IntegerField(blank=True, null=True, verbose_name='Азот нитратов')),
                ('nitrite', models.IntegerField(blank=True, null=True, verbose_name='Азот нитритов')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component2', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component2', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая')),
                ('oxidability', models.IntegerField(blank=True, null=True, verbose_name='Окисляемость')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('chlorine', models.IntegerField(blank=True, null=True, verbose_name='Остаточный хлор')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component3', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component3', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('suspended_solids', models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Фосфор')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Сульфаты')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая')),
                ('hardness_magnesium', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость магниевая')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component4', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component4', to='projects.watertype')),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='result',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sampling_site',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
