# Generated by Django 4.0.3 on 2022-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_inputcomponent12_inputcomponent13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputComponent21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общая жесткость')),
                ('input_component2', models.IntegerField(verbose_name='Кальциевая жесткость')),
                ('input_component3', models.IntegerField(verbose_name='Значение рН')),
                ('input_component4', models.IntegerField(verbose_name='Общее солесодержание')),
                ('input_component5', models.IntegerField(verbose_name='Содержание хлоридов')),
                ('input_component6', models.IntegerField(verbose_name='Содержание сульфатов')),
                ('input_component7', models.IntegerField(verbose_name='Содержание нефтепродуктов')),
                ('input_component8', models.IntegerField(verbose_name='Общие взвешенные вещества')),
                ('input_component9', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component10', models.IntegerField(verbose_name='Железо')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [2|1]',
                'verbose_name_plural': 'Input | Компонент [2|1]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общая жесткость')),
                ('input_component2', models.IntegerField(verbose_name='Кальциевая жесткость')),
                ('input_component3', models.IntegerField(verbose_name='Значение рН')),
                ('input_component4', models.IntegerField(verbose_name='Общее солесодержание')),
                ('input_component5', models.IntegerField(verbose_name='Содержание хлоридов')),
                ('input_component6', models.IntegerField(verbose_name='Содержание сульфатов')),
                ('input_component7', models.IntegerField(verbose_name='Содержание нефтепродуктов')),
                ('input_component8', models.IntegerField(verbose_name='Общие взвешенные вещества')),
                ('input_component9', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component10', models.IntegerField(verbose_name='Железо')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [2|2]',
                'verbose_name_plural': 'Input | Компонент [2|2]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent31',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общая жесткость')),
                ('input_component2', models.IntegerField(verbose_name='Кальциевая жесткость')),
                ('input_component3', models.IntegerField(verbose_name='Значение рН')),
                ('input_component4', models.IntegerField(verbose_name='Общее солесодержание')),
                ('input_component5', models.IntegerField(verbose_name='Содержание хлоридов')),
                ('input_component6', models.IntegerField(verbose_name='Содержание сульфатов')),
                ('input_component7', models.IntegerField(verbose_name='Содержание нефтепродуктов')),
                ('input_component8', models.IntegerField(verbose_name='Общие взвешенные вещества')),
                ('input_component9', models.IntegerField(verbose_name='Щелочность по фенолу')),
                ('input_component10', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component11', models.IntegerField(verbose_name='Железо')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [3|1]',
                'verbose_name_plural': 'Input | Компонент [3|1]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent41',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общие взвешенные твердые частицы')),
                ('input_component2', models.IntegerField(verbose_name='Хлориды')),
                ('input_component3', models.IntegerField(verbose_name='Сульфаты')),
                ('input_component4', models.IntegerField(verbose_name='Значение рН')),
                ('input_component5', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component6', models.IntegerField(verbose_name='Жесткость кальциевая (кальций, мг/л)')),
                ('input_component7', models.IntegerField(verbose_name='Жесткость общая')),
                ('input_component8', models.IntegerField(verbose_name='Железо общее')),
                ('input_component9', models.IntegerField(verbose_name='Солесодержание')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [4|1]',
                'verbose_name_plural': 'Input | Компонент [4|1]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent42',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общие взвешенные твердые частицы')),
                ('input_component2', models.IntegerField(verbose_name='Значение рН')),
                ('input_component3', models.IntegerField(verbose_name='Хлориды')),
                ('input_component4', models.IntegerField(verbose_name='Фосфор')),
                ('input_component5', models.IntegerField(verbose_name='Нефтепродукт')),
                ('input_component6', models.IntegerField(verbose_name='Щелочность общая')),
                ('input_component7', models.IntegerField(verbose_name='Жесткость кальциевая (кальций, мг/л)')),
                ('input_component8', models.IntegerField(verbose_name='Жесткость общая')),
                ('input_component9', models.IntegerField(verbose_name='Железо общее')),
                ('input_component10', models.IntegerField(verbose_name='Солесодержание')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [4|2]',
                'verbose_name_plural': 'Input | Компонент [4|2]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent43',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общие взвешенные твердые частицы')),
                ('input_component2', models.IntegerField(verbose_name='Хлориды')),
                ('input_component3', models.IntegerField(verbose_name='Сульфаты')),
                ('input_component4', models.IntegerField(verbose_name='Значение рН')),
                ('input_component5', models.IntegerField(verbose_name='Фосфор')),
                ('input_component6', models.IntegerField(verbose_name='Щелочность')),
                ('input_component7', models.IntegerField(verbose_name='Жесткость кальциевая (кальций, мг/л)')),
                ('input_component8', models.IntegerField(verbose_name='Жесткость общая')),
                ('input_component9', models.IntegerField(verbose_name='Железо общее')),
                ('input_component10', models.IntegerField(verbose_name='Солесодержание')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [4|3]',
                'verbose_name_plural': 'Input | Компонент [4|3]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent44',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Остаточный хлор')),
                ('input_component2', models.IntegerField(verbose_name='Нефтепродукт')),
                ('input_component3', models.IntegerField(verbose_name='Солесодержание')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [4|4]',
                'verbose_name_plural': 'Input | Компонент [4|4]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent45',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Общие взвешенные твердые частицы')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [4|5]',
                'verbose_name_plural': 'Input | Компонент [4|5]',
            },
        ),
    ]
