# Generated by Django 4.0.3 on 2022-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_tasks_task_alter_taskassign_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название компонента'),
        ),
    ]
