# Generated by Django 4.0.4 on 2022-04-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_component_period_in_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingsite',
            name='water_type',
        ),
        migrations.AddField(
            model_name='samplingsite',
            name='water_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_site', to='projects.watertype'),
            preserve_default=False,
        ),
    ]
