# Generated by Django 4.0.3 on 2022-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_taskassign_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название компонента'),
        ),
    ]
