# Generated by Django 4.0.3 on 2022-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_inputcomponent21_inputcomponent22_inputcomponent31_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputComponent51',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Нефтепродукт')),
                ('input_component2', models.IntegerField(verbose_name='Взвешенные вещества')),
                ('input_component3', models.IntegerField(verbose_name='Значение рН')),
                ('input_component4', models.IntegerField(verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('input_component5', models.IntegerField(verbose_name='Поверхностно-активные вещества (АПАВ)')),
                ('input_component6', models.IntegerField(verbose_name='Аммонийный азот')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [5|1]',
                'verbose_name_plural': 'Input | Компонент [5|1]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent61',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Значение рН')),
                ('input_component2', models.IntegerField(verbose_name='Взвешенные вещества')),
                ('input_component3', models.IntegerField(verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('input_component4', models.IntegerField(verbose_name='Нефтепродукт')),
                ('input_component5', models.IntegerField(verbose_name='Биологическая потребность в кислороде (БПК5)')),
                ('input_component6', models.IntegerField(verbose_name='Фенолы')),
                ('input_component7', models.IntegerField(verbose_name='Поверхностно-активные вещества  (АПАВ)')),
                ('input_component8', models.IntegerField(verbose_name='Хлориды')),
                ('input_component9', models.IntegerField(verbose_name='Сульфаты')),
                ('input_component10', models.IntegerField(verbose_name='Железо')),
                ('input_component11', models.IntegerField(verbose_name='Аммонийный азот')),
                ('input_component12', models.IntegerField(verbose_name='Азот нитратов')),
                ('input_component13', models.IntegerField(verbose_name='Азот нитритов')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [6|1]',
                'verbose_name_plural': 'Input | Компонент [6|1]',
            },
        ),
        migrations.CreateModel(
            name='InputComponent62',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_component1', models.IntegerField(verbose_name='Щёлочность общая')),
                ('input_component2', models.IntegerField(verbose_name='Жёсткость общая')),
                ('input_component3', models.IntegerField(verbose_name='Окисляемость')),
                ('input_component4', models.IntegerField(verbose_name='Солесодержание')),
                ('input_component5', models.IntegerField(verbose_name='Остаточный хлор')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input | Компонент [6|2]',
                'verbose_name_plural': 'Input | Компонент [6|2]',
            },
        ),
    ]
