# Generated by Django 4.0.3 on 2022-03-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_componentssite1_componentssite2_componentssite3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentssite1',
            name='active_subst',
        ),
        migrations.RemoveField(
            model_name='componentssite1',
            name='ammonium',
        ),
        migrations.RemoveField(
            model_name='componentssite1',
            name='oxygen_chem',
        ),
        migrations.RemoveField(
            model_name='componentssite1',
            name='suspended_subst',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='active_subst',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='ammonium',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='chlorides',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='nitrate',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='nitrite',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='oxygen_bio',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='oxygen_chem',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='phenols',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='sulfates',
        ),
        migrations.RemoveField(
            model_name='componentssite2',
            name='suspended_subst',
        ),
        migrations.RemoveField(
            model_name='componentssite3',
            name='chlorine',
        ),
        migrations.RemoveField(
            model_name='componentssite3',
            name='oxidability',
        ),
        migrations.RemoveField(
            model_name='componentssite4',
            name='hardness_magnesium',
        ),
        migrations.RemoveField(
            model_name='componentssite4',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='componentssite4',
            name='suspended_solids',
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='alkalinity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='hardness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='hardness_magnesium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость магниевая'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Железо'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='phosphorus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фосфор'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='salt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Солесодержание'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AddField(
            model_name='componentssite1',
            name='suspended_solids',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы'),
        ),
        migrations.AddField(
            model_name='componentssite2',
            name='suspended_solids',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='dry_residue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сухой остаток'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='hardness_magnesium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жёсткость магниевая'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Железо'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='ph',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение pH'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AddField(
            model_name='componentssite3',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества'),
        ),
        migrations.AddField(
            model_name='componentssite4',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общие Взвешенные вещества'),
        ),
        migrations.AlterField(
            model_name='componentssite1',
            name='ph',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение pH'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='chlorides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Содержание хлоридов'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='hardness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая жесткость'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='hardness_calcium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='oil_prod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Содержание нефтепродуктов'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='salt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее солесодержание'),
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='sulfates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Содержание сульфатов'),
        ),
        migrations.CreateModel(
            name='ComponentsSite9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_solids', models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Сульфаты')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Фосфор')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость (кальций, мг/л)')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо общее')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component9', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component9', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_solids', models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Фосфор')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость (кальций, мг/л)')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо общее')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component8', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component8', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_solids', models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Сульфаты')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость (кальций, мг/л)')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жесткость общая')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо общее')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component7', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component7', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Общая жесткость')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Общее солесодержание')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Содержание хлоридов')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Содержание сульфатов')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Содержание нефтепродуктов')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Общие Взвешенные вещества')),
                ('alkalinity_phenols', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность по фенолу')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component6', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component6', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Общая жесткость')),
                ('hardness_calcium', models.IntegerField(blank=True, null=True, verbose_name='Кальциевая жесткость')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Общее солесодержание')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Содержание хлоридов')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Содержание сульфатов')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Содержание нефтепродуктов')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Общие Взвешенные вещества')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component5', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component5', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alkalinity', models.IntegerField(blank=True, null=True, verbose_name='Щёлочность общая')),
                ('hardness', models.IntegerField(blank=True, null=True, verbose_name='Жёсткость общая')),
                ('oxidability', models.IntegerField(blank=True, null=True, verbose_name='Окисляемость')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('chlorine', models.IntegerField(blank=True, null=True, verbose_name='Остаточный хлор')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component14', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component14', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='Значение pH')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('active_subst', models.IntegerField(blank=True, null=True, verbose_name='Поверхностно-активные вещества (АПАВ)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('oxygen_bio', models.IntegerField(blank=True, null=True, verbose_name='Биологическая потребность в кислороде (БПК5)')),
                ('phenols', models.IntegerField(blank=True, null=True, verbose_name='Фенолы')),
                ('chlorides', models.IntegerField(blank=True, null=True, verbose_name='Хлориды')),
                ('sulfates', models.IntegerField(blank=True, null=True, verbose_name='Сульфаты')),
                ('iron', models.IntegerField(blank=True, null=True, verbose_name='Железо')),
                ('nitrate', models.IntegerField(blank=True, null=True, verbose_name='Азот нитратов')),
                ('nitrite', models.IntegerField(blank=True, null=True, verbose_name='Азот нитритов')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component13', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component13', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('ph', models.IntegerField(blank=True, null=True, verbose_name='pH')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('active_subst', models.IntegerField(blank=True, null=True, verbose_name='Поверхностно-активные вещества (АПАВ)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component12', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component12', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_solids', models.IntegerField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component11', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component11', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chlorine', models.IntegerField(blank=True, null=True, verbose_name='Остаточный хлор')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='Солесодержание')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component10', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component10', to='projects.watertype')),
            ],
        ),
    ]
