# Generated by Django 4.0.4 on 2022-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_samplingsite_water_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingsite',
            name='water_type',
        ),
        migrations.AddField(
            model_name='samplingsite',
            name='water_type',
            field=models.ManyToManyField(related_name='sampling_site', to='projects.watertype'),
        ),
    ]
