# Generated by Django 4.0.3 on 2022-03-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_component_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='limits',
        ),
        migrations.AddField(
            model_name='component',
            name='limit_hi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не более'),
        ),
        migrations.AddField(
            model_name='component',
            name='limit_lo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не ниже'),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения задачи в часах'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи'),
        ),
    ]
