# Generated by Django 4.0.3 on 2022-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_component_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок выполнения задачи в часах'),
        ),
    ]
