# Generated by Django 4.0.3 on 2022-04-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_samplingsite_water_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsSite16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Фосфор')),
                ('oxygen_bio', models.IntegerField(blank=True, null=True, verbose_name='Биологическая потребность в кислороде (БПК5)')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component16', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component16', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsSite15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_subst', models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества')),
                ('oil_prod', models.IntegerField(blank=True, null=True, verbose_name='Нефтепродукт')),
                ('oxygen_chem', models.IntegerField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)')),
                ('ammonium', models.IntegerField(blank=True, null=True, verbose_name='Аммонийный азот')),
                ('phosphorus', models.IntegerField(blank=True, null=True, verbose_name='Фосфор')),
                ('oxygen_bio', models.IntegerField(blank=True, null=True, verbose_name='Биологическая потребность в кислороде (БПК5)')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время пробы')),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component15', to='projects.samplingsite')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_component15', to='projects.watertype')),
            ],
        ),
    ]
