# Generated by Django 3.2.13 on 2022-04-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_samplingsite_water_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycled_water_consumption', models.IntegerField(blank=True, null=True, verbose_name='Расход оборотной воды')),
                ('running_water_consumption', models.IntegerField(blank=True, null=True, verbose_name='Расход подпиточной воды')),
                ('purge_flow', models.IntegerField(blank=True, null=True, verbose_name='Расход продувки')),
                ('hot_water_temp', models.IntegerField(blank=True, null=True, verbose_name='Температура горячей оборотной воды')),
                ('cold_water_temp', models.IntegerField(blank=True, null=True, verbose_name='Температура охлажденной воды')),
                ('total_microbial_number', models.IntegerField(blank=True, null=True, verbose_name='Общее микробное число')),
                ('plant_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_component', to='projects.plantunit')),
            ],
        ),
    ]
