# Generated by Django 4.0.3 on 2022-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_execution_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassign',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи'),
        ),
    ]
