# Generated by Django 3.2.13 on 2022-04-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_additionalcomponents'),
        ('projects', '0007_componentssite16_componentssite15'),
    ]

    operations = [
    ]
