# Generated by Django 3.2.13 on 2022-04-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge_20220427_1838'),
        ('projects', '0008_merge_20220428_1408'),
    ]

    operations = [
    ]
