# Generated by Django 4.0.3 on 2022-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_taskassign_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='limits',
        ),
        migrations.AddField(
            model_name='component',
            name='limit_hi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не более'),
        ),
        migrations.AddField(
            model_name='component',
            name='limit_lo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не ниже'),
        ),
    ]
