# Generated by Django 3.2.13 on 2022-05-03 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20220428_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcomponents',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время пробы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentssite4',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества'),
        ),
        migrations.AlterField(
            model_name='componentssite5',
            name='suspended_subst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Взвешенные вещества'),
        ),
    ]
