# Generated by Django 4.0.3 on 2022-03-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_component_limits_component_limit_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='limits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Допустимые нормы не ниже'),
        ),
    ]
