# Generated by Django 4.0.3 on 2022-03-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_component_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='limits',
        ),
    ]
