# Generated by Django 4.0.3 on 2022-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_notification_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationassign',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationassign',
            name='user',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='comp_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компонента'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationAssign',
        ),
    ]
