# Generated by Django 3.2.13 on 2022-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_additionalcalculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='calcium_hardness_transport',
            field=models.FloatField(blank=True, null=True, verbose_name='Транспорт кальциевой жесткости'),
        ),
        migrations.AlterField(
            model_name='additionalcalculations',
            name='drip_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Капельный унос'),
        ),
        migrations.AlterField(
            model_name='additionalcalculations',
            name='evaporation_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент упаривания'),
        ),
        migrations.AlterField(
            model_name='additionalcalculations',
            name='evaporative_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Потери с испарением'),
        ),
        migrations.AlterField(
            model_name='additionalcalculations',
            name='purge_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем продувки'),
        ),
        migrations.AlterField(
            model_name='additionalcalculations',
            name='unauthorized_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Несанкционированные потери'),
        ),
    ]
