# Generated by Django 3.2.13 on 2022-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220511_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentssite',
            name='active_subst',
            field=models.FloatField(blank=True, null=True, verbose_name='Поверхностно-активные вещества (АПАВ)'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='alkalinity',
            field=models.FloatField(blank=True, null=True, verbose_name='Щёлочность общая'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='alkalinity_phenols',
            field=models.FloatField(blank=True, null=True, verbose_name='Щёлочность по фенолу'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='ammonium',
            field=models.FloatField(blank=True, null=True, verbose_name='Аммонийный азот'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='chlorides',
            field=models.FloatField(blank=True, null=True, verbose_name='Хлориды'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='chlorine',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаточный хлор'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='dry_residue',
            field=models.FloatField(blank=True, null=True, verbose_name='Сухой остаток'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='hardness',
            field=models.FloatField(blank=True, null=True, verbose_name='Жёсткость общая'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='hardness_calcium',
            field=models.FloatField(blank=True, null=True, verbose_name='Жёсткость кальциевая'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='hardness_magnesium',
            field=models.FloatField(blank=True, null=True, verbose_name='Жёсткость магниевая'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='iron',
            field=models.FloatField(blank=True, null=True, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='nitrate',
            field=models.FloatField(blank=True, null=True, verbose_name='Азот нитратов'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='nitrite',
            field=models.FloatField(blank=True, null=True, verbose_name='Азот нитритов'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='oil_prod',
            field=models.FloatField(blank=True, null=True, verbose_name='Нефтепродукт'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='oxidability',
            field=models.FloatField(blank=True, null=True, verbose_name='Окисляемость'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='oxygen_bio',
            field=models.FloatField(blank=True, null=True, verbose_name='Биологическая потребность в кислороде (БПК5)'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='oxygen_chem',
            field=models.FloatField(blank=True, null=True, verbose_name='Химическая потребность в кислороде (ХПК)'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение pH'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='phenols',
            field=models.FloatField(blank=True, null=True, verbose_name='Фенолы'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True, verbose_name='Фосфор'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='salt',
            field=models.FloatField(blank=True, null=True, verbose_name='Солесодержание'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='sulfates',
            field=models.FloatField(blank=True, null=True, verbose_name='Сульфаты'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='suspended_solids',
            field=models.FloatField(blank=True, null=True, verbose_name='Общие взвешенные твердые частицы'),
        ),
        migrations.AlterField(
            model_name='componentssite',
            name='suspended_subst',
            field=models.FloatField(blank=True, null=True, verbose_name='Взвешенные вещества'),
        ),
    ]
