# Generated by Django 4.0.3 on 2022-03-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_notificationassign_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='sampling_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.samplingsite'),
        ),
    ]
