# Generated by Django 3.2.13 on 2022-05-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20220517_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentssite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='input_component', to='auth.user'),
            preserve_default=False,
        ),
    ]
