# Generated by Django 3.2.13 on 2022-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_componentformula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentformula',
            options={'verbose_name': 'ComponentFormula', 'verbose_name_plural': 'ComponentFormula'},
        ),
        migrations.AddField(
            model_name='componentformula',
            name='measurement',
            field=models.CharField(default=1, max_length=50, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
