# Generated by Django 3.2.13 on 2022-07-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220705_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentformula',
            options={'verbose_name': 'ComponentFormula', 'verbose_name_plural': 'ComponentFormulas'},
        ),
    ]
