# Generated by Django 3.2.13 on 2022-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_componentformula_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentssite',
            name='halogen',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаточный галоген'),
        ),
    ]
