# Generated by Django 4.0.3 on 2022-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
