# Generated by Django 3.2.13 on 2022-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='auth.Group', verbose_name='Роль пользователя'),
        ),
    ]
