# Generated by Django 3.2.13 on 2022-08-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0019_componentssite_halogen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Задача')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выполнения задачи')),
                ('comp_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компонента')),
                ('comp_value', models.IntegerField(verbose_name='Показатель компонента')),
                ('notified', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.notification', verbose_name='Уведомление')),
                ('plant_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.plantunit', verbose_name='Установка')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible', to='auth.group', verbose_name='Ответственный')),
                ('sampling_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.samplingsite', verbose_name='Место отбора проб')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projects.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ChangesTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст изменения')),
                ('changed_to', models.CharField(max_length=200, verbose_name='На что изменил')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('failure_reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина невыполнения задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tasks.task')),
                ('who_changed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
        ),
    ]
