# Generated by Django 4.0.3 on 2022-04-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_remove_task_assignees_delete_comment_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Задача')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выполнения задачи')),
                ('comp_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компонента')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.notification', verbose_name='Уведомление')),
                ('plant_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.plantunit', verbose_name='Установка')),
                ('sampling_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.samplingsite', verbose_name='Место отбора проб')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='projects.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
