# Generated by Django 4.0.4 on 2022-04-15 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
