# Generated by Django 4.0.4 on 2022-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_changestracker_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comp_value',
            field=models.IntegerField(default=1, verbose_name='Показатель компонента'),
            preserve_default=False,
        ),
    ]
