# Generated by Django 4.0.4 on 2022-04-22 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_task_water_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='changestracker',
            name='changed_to',
            field=models.CharField(default=1, max_length=200, verbose_name='На что изменил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changestracker',
            name='who_changed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changestracker',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
