# Generated by Django 4.0.4 on 2022-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_changestracker_changed_to_changestracker_who_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changestracker',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина невыполнения задачи'),
        ),
    ]
